package example2;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;

public class App {

	public static void main(String[] args) {
		
		File file1 = new File("randomtext.txt");
		
		// The same code is executed this time using a try/catch block
		// It tries the code, if any FileNotFoundException is thrown it executes the code in the catch block
		// After executing the code in the catch block, it moves on to run code in the blocks below
		
		try {
			FileReader fileReader = new FileReader(file1);
			System.out.println("You have achieved success!");
		} catch (FileNotFoundException e) {
			System.out.println("File not found: " + file1.toString());
		}
		
		
		
		System.out.println("Catch block has finished excuting.");
		
		
		
	}

}
